### ISSUE TITLE
Review GPCE Draft

### ISSUE THREAD

**Issue by alhassy** [alhassy/next-700-module-systems#1]
@JacquesCarette and @WolframKahl, please.

**Comment by JacquesCarette** [comment]
If you're going to create issues, you ought to assign them!

**Comment by JacquesCarette** [comment]
This is now done. But weirdly, I can't close it myself. Why not?

**Comment by alhassy** [comment]
@JacquesCarette  and @WolframKahl 

As per JC's advice, I have avoided incorporating the many new design decisions of the prototype since the paper was submitted. However, I have updated the obsolete portions so that the paper is not mostly useless wrt to the current prototype implementation.

Please take a look at the PDF;  commit 810d10f.

**Comment by JacquesCarette** [comment]
Is the `Paper0.org` up to date?  I've noticed typos, that I can easily enough fix myself, but I don't want to edit a stale file.

**Comment by JacquesCarette** [comment]
Also, why are there no references in the generated PDF?  There's a lot of stuff to edit - grammar mistakes, nonsensical sentences, overly chatty sentences, overly editorial sentences [without evidence to back up the opinion]. And those are just the ones I caught, @WolframKahl might catch others.

**Comment by alhassy** [comment]
For future reference, always assume the repo contains up to date content. Merge conflicts are acceptable.

Feedback, either on the PDF or org-mode or even in an arbitrary text file or scrap of paper is appreciated.

It is a small PDF, you may not have found them where you expected them to be, but they are there.

A hardcopy can be provided if you would like one.

**Comment by JacquesCarette** [comment]
Done.  It makes sense to open a separate one for Wolfram to do.
