### ISSUE TITLE
Progressing towards a type theory for PackageFormers

### ISSUE THREAD

**Issue by alhassy** [alhassy/next-700-module-systems#25]
Please take a look at `prototype/pf.agda`, line ~250 has a `JC` clause.

Please provide guidance and feedback.

**Comment by JacquesCarette** [comment]
I gave quick look - couldn't solve the problem right away.  I will look again.

Certainly my instinct is that you're "climbing up" levels too fast -- Set2 should not be needed here. Though it is definitely not clear how to fix that.

I would also (re)read [Shallow Embedding of Type Theory is Morally Correct](https://arxiv.org/abs/1907.07562).

**Comment by JacquesCarette** [comment]
I tried harder[fired up Agda], but nothing typechecks, so I can't really help.  I'm using 2.6.0.1 - what version are you using?

**Comment by WolframKahl** [comment]
There is also a ton of other stuff, including examples, interspersed in the middle of your huge mutually-recursive datatype definition. Please move out everything that is not needed inside that mutual recursion, and document the need for items that are needed inside there.

**Comment by alhassy** [comment]
Any feedback about the direction sketched [here](
https://github.com/alhassy/next-700-module-systems/blob/master/prototype/theory.lagda.org#semantics-via-ma-sets)?

Thanks!

**Comment by WolframKahl** [comment]
The “i.e.” in the first sentence/paragraph is completely unclear to me.

The “we define” is also surprising, since no definition of `Declaration` is in sight,
and the second paragraph goes off in a completely different direction without any motivation provided for that.

What is the plan here?

And why are the code fragments declared as `haskell` in the source?

**Comment by JacquesCarette** [comment]
There is way too much information left implicit. I know what you're working on, and yet I can barely read this and make sense of it.  Maybe you should prepare a talk about this (yes, with slides and all) and present it to Wolfram and I.

Don't get me wrong: this could be great (content-wise). Or, it could be flawed -- I just can't tell from this haphazard writeup.

**Comment by alhassy** [comment]
Thanks for the feedback guys!

In an effort to reduce the haziness, I've formalised my thoughts in Agda ---which ought to be less ambiguous. Besides the org-file, there's also a new .agda file. Everything typechecks.

The plan is what I wanted to confirm with the previous commit. In particular, whether the approach I'm taking is reasonable or not. To be clear, I'm trying yet a new approach via initial semantics.

**Comment by WolframKahl** [comment]
`Context = Set` needs explanation.

If `C : Context` and `x : C`, what kind of thing is `x`?
(A variable?)

Why is `type = Context'`?

`record PackageFormer` implements `:waist`, but not `:kind`?

**Comment by JacquesCarette** [comment]
**Everything** needs an explanation.  Sure, the code seems reasonable at first blush, but since there is no narrative that starts "from the beginning", I can't actually evaluate if the code matches what you're actually trying to do.  My 'implicit' comment above has not been addressed in any way - maybe even made worse.

Just as one example: I'm kind of surprised that the type-theory over which you are parametric is 1) unbundled, and 2) so generic. I would think that you would need it to have more properties, and so need to have a few more assumptions (and so eventually bundle it, as the number of parameters gets unwieldly).

And, of course, if you'd peppered your development with comments, you would have both left explanations for things that Wolfram asked about **and** references to the literature as to why that's a sensible thing to do.

**Comment by WolframKahl** [comment]
What is the canonical flattened form of
````
    (∅ ⨾ n₀ ∶ τ₀ ≔ d₀ ⨾ ⋯ ⨾ nₘ ∶ τₘ ≔ dₘ ⟴ :waist 𝓌 ⟴ :kind 𝓀) ⨾ n ∶ τ ≔ d
````
?

What is the canonical flattened form of
````
    (∅ ⨾ n₀ ∶ τ₀ ≔ d₀ ⨾ ⋯ ⨾ nₘ ∶ τₘ ≔ dₘ ⟴ :waist 𝓌 ⟴ :kind 𝓀) ⨾ ⟴ :waist ᵤ
````
?

What is the canonical flattened form of
````
    (∅ ⨾ n₀ ∶ τ₀ ≔ d₀ ⨾ ⋯ ⨾ nₘ ∶ τₘ ≔ dₘ ⟴ :waist 𝓌 ⟴ :kind 𝓀) ⨾ ⟴ :kind g
````
?

**Comment by WolframKahl** [comment]
Since you combine contexts with `_⊎_`, I wonder why you have `∅ = ⊤` for what I guess is intended to be the empty context, and not `⊥`.

**Comment by JacquesCarette** [comment]
My guess: because `_⊎_` is a bad choice of symbols, `_++_` would be more accurate. It's product-like, not coproduct-like.

**Comment by WolframKahl** [comment]
I'm not convinced...

Let's see what Musa says...

(and when...)

**Comment by alhassy** [comment]
Thanks for the useful feedback gang!

@JacquesCarette 
+ [X] Good call on shallow semantics, that's what I'm tying now.
+ [X] I'm using Agda 2.6.0.1
  - Everything in the recently committed file typechecks.
+ [X] There's an “Introduction” section in the `theory.org` file, which renders
  nicely on GitHub. It aims to make clear what I'm trying to do.
+ [X] A narrative has been imposed: No code block exceeding 13 lines is present
  in the literate document.
+ [X] I was trying to get a feel for what is needed for a type theory; good call
  on the bundling.
+ [X] The narrative attempts to explain that we're using Agda's type theory to do
  a lot of the heavy lifting. See §4, “Our Ambient Type Theory”.
  - This is why the mention of type theories was so generic.

@WolframKahl 
+ [X] Documentation, examples, and code are all living in an Org file.
  - Raw Agda code is tangled to a `.agda` file, which is < 120 lines and typechecks
+ [X] An Agda type for `Declaration` is now provided, under `TypeTheory`.
+ [X] Some code fragments are marked with `haskell` since the are informal
  and I did not want them to be picked up by Agda in `.lagda.org` files
  which does not support Org's `:tangle no` feature.
  - Additionally, Haskell provides some syntax highlighting whereas Agda blocks
    do not.
+ [ ] I could not locate the phrase `type = Context` in the previous commit.
+ [X] Design decisions have been explained in the org file, which renders nicely
  on GitHub.
+ [ ] For brevity, I'm only considering `waist` for now.
+ [ ] Here are some laws that allow one to reach the claimed canonical form:
  1. `:waist w ⟴ :kind k ≈ :kind k ⟴ :waist w`

     Hence, we can always ensure `waist` appears before `kind`.

  2. More generally, `f ⟴ g ≈ g ⟴ f` whenever `f` and `g` are ‘disjoint’; whence
     ⨾-extensions also share this property with `:waist` and `:kind`.

     Thus we can always ensure ⨾-extensions appear before `:waist` and `:kind` clauses.

  3. `f₁ ⟴ f₂ ≈ f₂` for `fᵢ` both being either `:waist` clauses or `:kind` clauses.

     Hence, there will always be only one `:waist` and one `:kind` clause.

  Of-course these rules only permit the constructions `⟴, :waist, :kind` and   ⨾-extensions. E.g., if the hammer `:alter-elements` is admitted, then little  can be said since, say, one may re-arrange ⨾-extension elements according to  their waist and kind, as is the case of Agda modules, wherein items above  the waist *cannot* have definitional clauses.

+ [X] The use of sums may not be appropriate, but ⊥ is unquestionably not the
    choice of representative for empty contexts ---this confusion is due to
    my initial lack of a narrative, which is now remedied.

I'm looking forward to your feedback ^_^

**Comment by JacquesCarette** [comment]
Excellent.  When you say 'renders nicely on github', providing a link would have been extra-useful, so that we don't err and look at the wrong file(s).  Can you indeed provide that link?

**Comment by JacquesCarette** [comment]
Do you mean https://github.com/alhassy/next-700-module-systems/blob/master/prototype/theory.org ?

**Comment by WolframKahl** [comment]
> When Γ is fixed and if we denote Γ ⊢ e ∶ τ by e ⟶ τ then we obtained a directed graph 

A free variable relation `isFreeIn : REL Var Expr` would be needed for that.

>  It seems that with the typing judgement, we can regain the kinding judgement: Γ ⊢ τ type ⇔ ∀ (v : 𝕍) → Γ ⊢ v ∶ τ.

If this is true, then your contexts and judgements work completely differently than I am used to.

**Comment by WolframKahl** [comment]
You have very strange implicit/explicit argument choices in:
````
data Declaration (Γ : Context) : Set where
  _∶_≔_ : (n : 𝕍) {τ δ : Expr Γ} → Γ ⊢ τ type → Γ ⊢ δ ∶ τ → Declaration Γ
````
Since you probably won't have decision procedures for the judgements,
I would make everything explicit, e.g.:
````
data Declaration (Γ : Context) : Set where
  _∶_≔_by_and_ : (n : 𝕍) (τ δ : Expr Γ) → Γ ⊢ τ type → Γ ⊢ δ ∶ τ → Declaration Γ
````
Or have a separate well-formedness predicate:
````
data Declaration (Γ : Context) : Set where
  _∶_≔_ : (n : 𝕍) (τ δ : Expr Γ) → Γ ⊢ τ type → Γ ⊢ δ ∶ τ → Declaration Γ
data DeclarationWF (Γ : Context) : Set where
   declarationIsWellFormed : (n : 𝕍) {τ δ : Expr Γ} → Γ ⊢ τ type → Γ ⊢ δ ∶ τ → DeclarationWF Γ (n ∶ τ  ≔ δ )
````

**Comment by WolframKahl** [comment]
> With the ‘smart constructors’ below, a context is a dependent product of types wherein later type-declarations may depend on earlier ones.

See the discussion of the term “dependent product” in https://plfa.github.io/Quantifiers/ .

**Comment by WolframKahl** [comment]
In the light of what we discussed yesterday: As far as your shallow embedding only considers record semantics, please declare that up-front.

Because  “not considering kind for the time being” is quite different from
“implementing only the record kind for the time being”.

**Comment by JacquesCarette** [comment]
Strong agreement.

**Comment by WolframKahl** [comment]
None of the current examples uses `_>>_`.

I don't trust its definition...

**Comment by WolframKahl** [comment]
What is the relation between `record TypeTheory` and the section `Our Ambient Type Theory`?

Beyond the definition of `Context`, I cannot discern any attempt to implement a record of type `TypeTheory`...

**Comment by WolframKahl** [comment]
`example₄` does not use a smart constructor for the argument of `TwoParameterPoints`!

**Comment by WolframKahl** [comment]
Better:
```
example₆ = ℕ , ℕ._+_ , 4 , 8 , refl {x = 8}
```
Adding a second law might be an opportunity to use `_>>_`...

**Comment by WolframKahl** [comment]
> Magma Example – A record with (simulated) definitions

Better:

Example – A record type with one invariant

**Comment by alhassy** [comment]
The smart constructors are for forming Contexts, not for instances of contexts. I've aimed to clarify that.

I've also pointed out that the smart constructors are what we actually use to construct our examples: The do notation is just inlined definitions of the smart constructors ;-)

**Comment by WolframKahl** [comment]
Since in
```
example₄ : TwoParameterPoints 𝔹
```
, `𝔹 : Context`, I would have emphasised that by, e.g.,
````
example₄ : TwoParameterPoints (Lit 𝔹)
````
, with
```
Lit : Set → Context   -- Literal datatypes.
Lit = id
```
.

**Comment by WolframKahl** [comment]
What you call
```
                        -- ‘Definitions’
```
, I would call `Invariants`. They are proof obligations at instance construction time, and available as properties for given instances, but not in the way that definitions would be available.

In particular, there is nothing that restricts these invariants to equations, and non-equations will be useful as invariants, too.

So for dealing with definitions, I think that a different way has to be found.

**Comment by WolframKahl** [comment]
You could define `_>>=_` and `End` as aliases for  `_⨾_` and `∅`.

**Comment by WolframKahl** [comment]
````
infix -1000 Property_
Property_ : Set → Context   -- Intended as invariants.
Property_ = id              -- In some contexts, the values could be irrelevant.
````
Then:
````
PointedMagma : Context (ℓsuc ℓ0)
PointedMagma = do Carrier ← Set ℓ
                        _⊕_     ← (Carrier → Carrier → Carrier)
                        one     ← Carrier
                        two     ← Carrier
                        three   ← Carrier
                        Property    two   ≡ one ⊕ one
                        Property    three ≡ one ⊕ two
````
:wink:

**Comment by WolframKahl** [comment]
Try counting the waist from the other side (probably best one off):
````
(do Carrier <- Set
    e <- Carrier
    op <- Carrier -> Carrier
  ) (pred 1) = record (Carrier : Set) (e : Carrier) : Set where op : Carrier -> Carrier
(do Carrier <- Set
    e <- Carrier
    op <- Carrier -> Carrier
  ) (pred 2) = record (Carrier : Set) : Set where e : Carrier; op : Carrier -> Carrier
````
The left-association of `_>>=_` does not match the right-association of the function type constructor you want to use for parameters, so you have to either curry or accumulate / lift.

**Comment by WolframKahl** [comment]
Ah, the `do` translation parenthesises to the right!

>  the definition of _on_ seems ...

Which definition of `_on_`?

**Comment by WolframKahl** [comment]
````

open import Data.Bool using (Bool ; true ; false)

Collection : ∀ ℓ → Context (ℓsuc ℓ)
Collection ℓ = do
  Elem ← Set ℓ
  Carrier ← Set ℓ
  [] ← Carrier
  insert ← (Elem → Carrier → Carrier)
  isEmpty ← (Carrier → Bool)
  insert-nonEmpty ← ∀ {e : Elem} {x : Carrier} → isEmpty (insert e x) ≡ false
  End {ℓ}

open import Data.List using (List ; [] ; _∷_)

ListColl : {ℓ : Level} → Collection ℓ 1
ListColl E = List E , [] , (_∷_ , (λ { [] → true; _ → false}) , (λ {x} {x = x₁} → refl) , tt)
````

**Comment by alhassy** [comment]
The problem here is that one cannot speak of "collections whose element type is natural numbers'' via something like `Collection on N` or `Collection {Elem = N}` or `Collection :waist 1 N`; instead one must make a wrapper: `NCollection ... = (N, ...)`. This has the downside of *repeating* the definition of `Collection` in the types of `NCollection`'s arguments.

**Comment by WolframKahl** [comment]
What you have corresponds exactly to parameterised record types.

What you want there corresponds to a different `kind`, where, naively, you want to change the definition
```
(Γ >>= f) (suc n) = (γ : Γ n) → f γ n
```
to:
```
(Γ >>= f) (suc n) =  λ (γ : Γ n) → f γ n
```

**Comment by JacquesCarette** [comment]
Isn't the issue here closer to "in the encoding that I have chosen, the denotation of certain things are not functions (even though we might wish they were), so that this feature is not available"?  Part of the point of `:waist` would indeed be to lift certain things out to be parameters. 

Note that "parameter plugging" does **not** have to be done via function arguments!  You are allowed to design your own method of 'plugging'.

**Comment by WolframKahl** [comment]
Daring thought (with superfluous type signatures):
````
Elem : Collection ℓ 0 → Set ℓ
Elem = Field 0 Collection

Carrier : Collection ℓ 0 → Set ℓ
Carrier = Field 1 Collection

insert  : (C : Collection ℓ 0) → (Elem C → Carrier C → Carrier C)
insert = Field 3 Collection
````

**Comment by JacquesCarette** [comment]
As long as those 0, 1, 3 are from `Fin n` where `n` is the "size" of the `Collection`, that's a great thought.

**Comment by WolframKahl** [comment]
> As long as those 0, 1, 3 are from `Fin n` where `n` is the "size" of the `Collection`, that's a great thought.

Then the current 0, 1... should be from that `Fin n`, too --- probably a recommendable starting point.

**Comment by JacquesCarette** [comment]
The checklist above contains some unchecked items. Are they still live 'todo's?
