### ISSUE TITLE
4.1 overuse of bold

### ISSUE THREAD

**Issue by JacquesCarette** [alhassy/next-700-module-systems#30]
This is based on commit 2a1878f

On p.7, you use bold way too much. It is good to bold "Why Emacs?" and "Why Lisp?", but none of the rest requires bolding.

**Comment by alhassy** [comment]
The use of bold is to capture's the readers attention to key points; e.g., "seemelessly into the Agda interface" and "produce auxiliary files". 

Firstly, as has been an issue with readers who provide feedback after a cursory glance, such bold will serve to point out the important features of the section without having to force the readers in question to read the entire section: In effect, I'm striving to implicitly summarise the section by bolding key phrases and letting the reader see the phrase of interest and zoom-in to the associated paragraph to read more. 

Secondly, it seems that I have a habit of getting "too excited" and getting into related tangents that deserve to be relocated. As such, the use of bold phrases is an effort on my part to communicate to my readers what I believe are the main take aways from a section.

Finally, while it is the case that bold is not terribly popular in academic writing, I have personally found it to provide an "eye's view" of what I'm trying to communicate ---think of highlighted keywords in programming that quickly provide relevant control structure. However, the main reason that I have been empowered to use bold is actually by reading Florian Rabe's thesis. He uses bold as I have not seen it been used before; and while I thought it strange at first, as I kept reading, I found it useful and so adopted it. ( PDF link to his thesis may be found here: https://opus.jacobs-university.de/frontdoor/index/index/docId/344 )

As such, I'm not inclined to remove most of my bolded phrases. However, there are likely times when I am overemphasizing.

**Comment by JacquesCarette** [comment]
Please consider using \emph rather than \textbf for emphasis "often".  There's a reason it's called \emph...

Bold in the middle of text is somewhat akin to shouting. It is a good mechanism to use for material in up to about year 2 of university, but should be used sparingly after that. 

You might want to ask Florian if he still thinks that his use of bold in his thesis was a good idea. I'd be curious.

**Comment by alhassy** [comment]
Too much bold does look a bit strange ---reminiceint of a malfunctioning physical printer.

Perhaps what I will do would be to review 4.1, and other places, and see how much bold there is and use that as a signpost for improving an introductory (or maybe concluding!) paragraph that points out key ideas of the section.

**Comment by alhassy** [comment]
Stale; closing ---can be addressed on a case-by-case basis, if need be.
