### ISSUE TITLE
4.1 over-explanation of the design choices

### ISSUE THREAD

**Issue by JacquesCarette** [alhassy/next-700-module-systems#31]
This is based on commit 2a1878f

Given the need for a convenient prototype (see #29), doing it in elisp in emacs just makes sense. Yes, it's funny (and the comments to that effect can stay in), but you're over-justifying yourself.  There are 3-4 lines of text's worth of information on p.7. Try to make the explanation factual rather than 'aggressively defensive' of this reasonable design choice.

**Comment by alhassy** [comment]
No change.

Besides my supervisors, no one on my committee is familiar with Agda's
ecosystem. As such the one-sentence paragraph “Why Emacs?” is reasonable,
and factual.

Secondly, the “Why Lisp?” paragraph outlines important features of the interplay
between Emacs and Lisp that are unfortunately misunderstood by the general
computing community. For instance, I've seen online and discussed in person with
‘power users’ of Vi/Vim and other tools who believe that Elisp is simply a
configuration tool that is not comparable to a general programming language.
The truth couldn't be further.

While it may be over-justification to a seasoned Agda user, I doubt
that either of the fine points addressed by those paragraphs will
appear sufficiently trivial as to be justified by 4 lines of text.

Currently, those two paragraphs constitute 12 lines and you suggest cutting out
possibly two thirds of the content, which currently answer the following
questions:

1. Why Emacs?
2. Why ELisp?
   2.1 Isn't this just a DSL for configuring Emacs?
3. An editor extension provides editor support, how is this handled?
   3.1 What are they? Is there only one or more, perhaps provide terse examples.

If each question were to be answered in about 2 lines, we would reach about 10
lines ---pretty close to the existing 12 lines.

 I'm open to change if you explain your viewpoint ---e.g., “aggressively
 defensive” is how I would describe this reply of mine, but not exactly
 how I would describe the two paragraphs at the end of page 7.

**Comment by JacquesCarette** [comment]
Let me try to take a different approach: in your response above, you have points you'd like to make. Ok.  Questions:
1. do they 'fit' with the results in your thesis?
2. are they important to the main contributions of your thesis?
3. if they are, where is the right place to discuss these points? 

Here is an idea: condense the part where the point you're making is that your prototype is a reasonable way to proceed to the core arguments, and add commentary on emacs and elisp in a Discussion section at the end of this section. Basically because I do agree that discussing these things is good, but I also feel that they are not in the main core of your thesis. And thus by having them in the flow of the main exposition, distract the reader from your main points.

**Comment by alhassy** [comment]
I'll have to think on this a bit.

I like your idea of moving things to a discussion section, and that handy checklist is useful, but at the same time, but I still feel that the editor extension is a useful contribution of the thesis and so explaining why it was constructed as it was seems a bit relevant.  Non-Agda users (such as my committee) may wonder whether the choice of Emacs is random or not. As I type this reply, I do find that it may be better to move this content to a discussion section, but I'm not yet certain that it is not core material ---perhaps you can explain why you think it is not core?

I have read in places where authors use a particular tool or do something a particular way and do not care enough to share with the reader *why* they have chosen this particular route. Maybe I can mention that Emacs is suggested by the Agda ecosystem and leave more detail to the discussion section at the end of the chapter.

I'm not sure; I will let this settle for a bit.

**Comment by JacquesCarette** [comment]
Your prototype is indeed a useful contribution. Explaining it makes sense. Definitely explaining why it was constructed is needed.

My "problem" is you are mixing core material with non-core, in ways that seems confusing. Given the context (Agda development is mostly done in Emacs, working in Agda already involves manipulation of source code in Emacs (like the refine and case-split tactics), Emacs is configurable with a full-fledged programming language), it is very natural to consider extending these ideas.

I said that you are over-explaining this, not that you should not explain. The reasons to consider that approach are simple - they are right there in the above paragraph. 

Here is a different way to think of it: you're mixing the reasons to consider this approach, with the evaluation of the approach, and with the side-benefits of the approach.  i.e. a systematic (and in this case post-facto, but that's fine, that's normal) way to look at this:
1. what are the potential solutions?
2. what are the main pros and cons of these?
3. what extra things do we get from the chosen solution.

**Comment by alhassy** [comment]
This seems obsolete - closing.

**Comment by JacquesCarette** [comment]
I would not have described this as 'obsolete', but hopefully as *fixed*. You have made changes, in specific commits, to deal with this. So hopefully you could more confidently close this as such. Your closing it as obsolete does not inspire confidence - quite the opposite. But I will not re-open this one.
