### ISSUE TITLE
4.1 Why textual transformations? II

### ISSUE THREAD

**Issue by JacquesCarette** [alhassy/next-700-module-systems#33]
This is based on commit 2a1878f

Starting at "For instance, consider the Lisp term ...", the write-up now assumes that the reader knows Lisp. And that Lisp uses anaphoric macros instead of proper binders matters to the thesis - it really doesn't. [If it does, then this is not communicated here at all.]  I would delete this.

**Comment by alhassy** [comment]
It was intended as a bridge between Lisp and Agda/Haskell, no Lisp prerequistes were assumed. I'll change that.

However, the purpose of the example is not binders (macros included) but the fact that such constructs are not easy to assign a type to. It was just another example of why an untyped (Lisp) language is a reasonable option.

Perhaps I should add in the fact that the PackageFormer DSL is in-fact a Lisp DSL formed as anaphoric macros.

**Comment by JacquesCarette** [comment]
Right - you seem to have a point you want to make to the reader. From your comment above, I think I understand it (now).

"the purpose of the example is ... but the fact that ...": great, you know exactly what message you want to convey to your readers. Make sure that the section that is supposed to convey that message is focused on doing exactly and just that.  It does seem like a most sensible thing to convey, and does help to justify the 'reasonableness'.

Advice: make a list of the hard facts about the PackageFormer DSL you want your reader to know. Then make sure that you've conveyed that in a coherent, and hopefully connected manner. By connected, I mean that the list of ideas is not separated by other ideas that belong to a different topic.

Note that you absolutely may have a section in your chapters called 'discussion', where you do just that. This might be a good thing for you to explicitly do. That way you can keep the exposition of the facts and material sharply focused, but also have room to have more free-flowing prose commenting on the content itself. You'd still need to be able to either justify your opinions or mark some things clearly as "impressions" (i.e. unsubstantiated opinions arrived at through experience but without other means of justification).

**Comment by alhassy** [comment]
Okie dokes, I'll rewrite that with the suggested focus; and I like the idea of exposing selected facts about PF ^_^

I like this idea of top-level discussion sections. Would you please elaborate more on that idea ---e.g., what kind of content would go there, would it be meta-content, have you seen some of my writings that would ideally fall into such sections. Do you have a link where I can read more on such discussion sections? ^_^

**Comment by JacquesCarette** [comment]
I can't think of any particular paragraphs and/or sub-sections that were discussions. What I'm thinking is that you often throw in phrases (and sometimes it is even singular adjectives) which are really opinion / extremely brief 'discussion' into the middle of your writing. These distract from your main point.

But there are times where your added information / commentary is indeed valuable, just not inline. So if you make your text more direct by removing these distractors, it makes sense to have them re-appear as focused discussion (and opinion) in a separate section that will not distract from the flow and contributions. And still let you express yourself.

**Comment by alhassy** [comment]
Stale ;; good ideas for another life ---closing.
