### ISSUE TITLE
4.1 Why textual transformations? IV

### ISSUE THREAD

**Issue by JacquesCarette** [alhassy/next-700-module-systems#35]
This is based on commit 2a1878f

The last paragraph on p.8 contains very interesting information, but could be clearer.  Let me write a paragraph that I think says the same thing.

> Lisp uses a rather small number of constructs, such as macros and lambda, which themselves are used to build 'primitives', such as \texttt{defun} for defining top-level functions~\cite{XXX}. Knowing this about Lisp encourages us to emulate this expressive parsimony.

I did not use words like 'expected', 'minimal', 'orthogonal', 'day-to-day', on purpose. Because to use them, I would then have to **justify** them, and that is a unnecessary distraction.

**Comment by alhassy** [comment]
The text "Let over Lambda" points to Lisp's "meta-primitives" as its primary source of power.

I believe everything I wrote in that final paragraph of section 4.1. I believe it to all be true and accurate.

However, your phrasing does seem far more gentler.

**Comment by JacquesCarette** [comment]
The key phrases in my comment above are 'have to justify them' and 'unnecessary distraction'.  Simply being true is insufficient.

Meta point: communicate the items that are true, justifiable, and needed to understand the rest. If any of the 3 conditions is false, seriously question why you're trying to communicate it in your thesis.

That paragraph had very important things that needed to be communicated, but were decorated with items that failed the above 3-pronged test. You need to reread your own writings with this filter in mind, and I think you will be able to improve your write-up quite a bit.

**Comment by alhassy** [comment]
I like this 3-pronged test ---the third tail is where I fail a few times and that could be moved to a discussion section or removed altogether; the second tail seems to be a quick fix by the insertion of references.

**Comment by JacquesCarette** [comment]
Lots of relevant references is a good thing. It shows you know the literature, and thus implicitly convinces the reader that what you're doing must be new.

**Comment by alhassy** [comment]
Having been addressed, this seems obsolete - closing.
