### ISSUE TITLE
Is the title appropriate?

### ISSUE THREAD

**Issue by JacquesCarette** [alhassy/next-700-module-systems#36]
I think the thesis sub-title is fine, in that it is an adequate description of some of the results.  I don't think the title is.

**Comment by JacquesCarette** [comment]
Let me try to be more precise: while we originally started from the perspective of modules, as you meandered through the problem space and found various 'solutions', it is quite unclear to me that the end result is actually about modules.

Reading the pieces that are there, it is most definitely about "information capture", "information bundling", "transformations", and so on. But what appears more than anything else are records, not modules. In fact, records of a particular kind: they are mostly theory presentations. They are a big more than that, but that's certainly the center of gravity.

In particular, Chapter 4 very strongly has that flavour.

**Comment by alhassy** [comment]
Yes it is true that we mostly focus on theory presentations ---and maps between them and structural transformations on them--- however, afaik, "theory presentation" = "module".

I don't feel too strongly about the main title; for now it's intended as a "catchy title" and definitely better than the meme "next 700 module systems".

**Comment by alhassy** [comment]
Stale; closing ---the existing title is "good enough", but I'm open to suggestions.
