### ISSUE TITLE
Colour scheme confusion

### ISSUE THREAD

**Issue by JacquesCarette** [alhassy/next-700-module-systems#38]
The two diagrams in 4.1 (middle path and "how does it work") use similar colours, which confuses the reader (aka me) into thinking same-colour-same-meaning -- but this is quite false.

Two potential solution:
1. visual distance between the two diagrams, so that one isn't tempted to relate them
2. different colours in each, to not risk the confusion

**Comment by alhassy** [comment]
Oh, I didn't even consider that possibility! Thanks man; your suggestion about distance is what I'll do ;-)

**Comment by alhassy** [comment]
This is now obsolete - closing.

**Comment by JacquesCarette** [comment]
I would much much prefer if you instead were able to say "fixed in commit XXXXX". Because I think that's what you've done. Even if you've deleted both diagrams, that doesn't make the issue 'obsolete', it makes it 'fixed'. The only thing that would truly make it obsolete is if you decided to drop that chapter entirely (which I know you won't do!).  Please learn to treat issues properly.
