### ISSUE TITLE
Exageration in "the middle path"

### ISSUE THREAD

**Issue by JacquesCarette** [alhassy/next-700-module-systems#39]
Two points:
1. To a naive user, the IDE for Agda **is** the compiler.  Few ever use the raw compiler, so do not distinguish the editor interactions from Agda itself.
2. strictly speaking, the Prototype **is** a preprocessor. It is just integrated into the IDE, itself a preprocessor, in such a way that it does not feel like it. It is not a "manual command-line preprocessor", that is true.

In other words, the 3 circles picture is slightly more misleading than explanatory. [The text is not as imprecise.]  I would recommend deleting the 3 circles picture.  The arrow "How does it work" is fine.

**Comment by alhassy** [comment]
I agree with both of those points; yet disagree with the conclusion.

Here are other things that I believe to be true:

- Some people do execute their programs after manually executing a preprocessor,
- Some languages have a preprocessor built in
- Some languages have preprocessor-support as part of the dominant IDEs
- Some people do alter the compiler, or do make a preprocessor not silently part of the IDE

Perhaps the reason I have kept that diagram is that is is ``so connected in my own mind with the ideas that I was writing about that for me to deprive my readers of the connection that I myself felt so strongly would be nothing less than perverse.''  ;-)

**Comment by JacquesCarette** [comment]
Ok, let's then have a diagram that both of us agree reflects the situation properly.

Perhaps it is the Venn-like qualities of the diagram that I dislike? Maybe if it were laid out more like a 'spectrum' of choices, with perhaps more than 3 included, with your work lying "in the middle" but with characteristics of both ends (since it is a spectrum rather than a discrete choice), I would be happier?

**Comment by alhassy** [comment]
I agree that a spectrum is the way to go; good idea!

With your prompt of including more possibilities, I've produced a 2-dimensional spectrum, ie a plane. Then I stuck `PackageFormer` in a somewhat reasonable position `(•̀ᴗ•́)و`

**Comment by alhassy** [comment]
Closing since the 2-dimensional spectrum on p101, of the most recent commit, should suffice ---otherwise deletion is always an option.
