### ISSUE TITLE
Issue with exposition / example in 2.6

### ISSUE THREAD

**Issue by JacquesCarette** [alhassy/next-700-module-systems#9]
I can't see any difference in the output of `𝒱-primed-attempt` between 2.5 and 2.6. Most definitely no elision of repeated parts seem to be happening. Or maybe I'm expecting the wrong thing and the exposition is misleading me.

**Comment by alhassy** [comment]
There is intentionally no difference in resulting output;; issue tackled in commit 449156d19786802379a2acffd885bff351c3581c
